name: EKYD-DEV1-ENV-STATUS

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */12 * * *'
jobs:
  call-erp-soap:
    runs-on: ubuntu-latest
    steps:
    - name: Get Fusion EKYD REST API health
      run: |
        token=$(curl -s -X POST "${{ secrets.OAUTH_TOKEN_URL }}" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials" \
          -d "client_id=${{ secrets.OAUTH_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.OAUTH_CLIENT_SECRET }}" | jq -r '.access_token')
    
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Authorization: Bearer $token" \
          "https://ekyd-dev1.fa.em2.oraclecloud.com/fscmRestApi/resources/latest/")
    - name: Create json file Up
      run: |
                     cat <<EOF > Up.json
                        {
                          "id": 1,
                          "name": "Available"
                        }
                     EOF
    - name: Create json file Down
      run: |
                     cat <<EOF > Down.json
                         {
                            "id": 1,
                            "name": "Available"
                          }
                     EOF
    - name: Update Apwide with Fusion status
      run: |
        STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" "https://ekyd-dev1.fa.em2.oraclecloud.com")
           if [ "$STATUS" = "200" ]; then
           curl -X PUT "https://golive.apwide.net/api/status-change?environmentId=94&application=OFC%20EKYD-DEV1&category=Dev" \
                          -H "Authorization: Bearer ${{ secrets.APWIDE_GOLIVE_API_TOKEN }}" \
                          -H "Content-Type: application/json" \
                          -d @Up.json
              else
              curl -X PUT "https://golive.apwide.net/api/status-change?environmentId=94&application=OFC%20EKYD-DEV1&category=Dev" \
                -H "Authorization: Bearer ${{ secrets.APWIDE_GOLIVE_API_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d @Down.json
           fi
